# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      suite:
        type: string
        description: What suites to run

jobs:
  run-suites:
    runs-on: ubuntu-latest
    steps:
      - name: Run Regressions By Suite
        if: ${{ github.event.inputs.suite }}
        run: |
          echo "suites: ${{ github.event.inputs.suite }}"
      - name: Run Regressions
        if: ${{ !github.event.inputs.suite }}
        run: |
          echo "regressions running"
